media:
  input: src/files/media
  output: /files/media

content:
  - name: courses
    label: Courses
    path: src/_courses
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        options:
          minLength: 5
          maxLength: 256

      - name: description
        label: Description
        type: text

      - name: image
        label: Image
        type: image
        list: false
        options:
          path: src/files/media/courses
          categories: image
    view:
      fields: [title, description, image]
      sort: [date, title]
      default:
        sort: title
        order: desc